#!/bin/sh

#set -x
set -e

h=$(readlink -f $(dirname $0))
r=$(readlink -f $h/../..)
t=$r/tbs
d=MD5

export OCAMLRUNPARAM=b

if test $h = $PWD; then
    mkdir -p build
    cd build
fi

if ! md5sum --status -c $d; then
    md5sum $h/build.ml $h/tbs $t/tbs.cma >$d.tmp
    ocamlc.opt -o build.cmo -c -g -I $t $h/build.ml
    ocamlc.opt -g -thread -I $t unix.cma threads.cma tbs.cma build.cmo -o b
    mv $d.tmp $d
fi

cc="cc"
ccopt="-O"
test $(hostname) = "linmac" && {
    cc="$HOME/x/dev/gcc-4.3.0/bin/gcc";
    ccopt="-Wall -Werror -Wextra -O3 -mabi=altivec -maltivec -Wno-unused-function";
    ccopt="$ccopt -fprefetch-loop-arrays -mtune=power6 -mcpu=G4 -funroll-all-loops"
    ccopt="$ccopt -ftree-loop-linear -ftree-vectorize"
#    ccopt="$ccopt -DUSE_ALTIVEC"
    ccopt="$ccopt -DTIMING"
}

targets="dormin"
./b -O src:$h -r -O ccopt:"$ccopt" -O cc:$cc $* $targets
